### ISSUE TITLE
Right click doesn't work (Linux)

### ISSUE THREAD

**Issue by AutonomousCat** [allanrbo/filesremote#16]
Can't get right click to work. Running on Linux Mint in a Windows VirtualBox but all other uses of right click outside this window work. Right click seems to be treated as a left click for this specific program only.

**Comment by allanrbo** [comment]
What were you looking for right click to do? I didn't make any right click context menu, if that's what you were looking for. Instead I put all the functions as toolbar buttons in the top, and made shortcut keys.

**Comment by allanrbo** [comment]
Feel free to reply with what you wanted from right click, and we can perhaps reopen again. Closing otherwise.
