### ISSUE TITLE
Enhancement Request: Custom Editors for Different File Types

### ISSUE THREAD

**Issue by JJBT** [allanrbo/filesremote#20]
### Issue Description:
Hi there!

I'd like to propose a new feature to enhance our remote file access application. Currently, we have a single parameter, **Editor path**, which is applied for opening all file types. However, it would be great to add the capability to customize the editor (or **viewer**) for different file types.

### What Would Change:
Introduce a new feature to allow users to set different editors for various file types. Now users can specify separate editor paths for text files, images, videos, and other file formats.

### How it would work
* Introduce a new parameter Image viewer path.
* Introduce a new parameter Video viewer path.

Thanks!

**Comment by allanrbo** [comment]
Very nice suggestion! I'm not going to get time to implement this in the near future unfortunately, but here are some pointers if you want to take a go at making a pull request for this yourself:

This is the code that shows the text editor text field and label: https://github.com/allanrbo/filesremote/blob/389cd4d87ea996f42e8eca89db6352c0a58a2a1c/src/preferencespanel.cpp#L86-L98 . You could copy-paste this to make a new field for image and video viewer. Similarly a few other methods in this class would need updating to save/load from the config file.

This is the code that reads the editor path from the config and opens the editor: https://github.com/allanrbo/filesremote/blob/389cd4d87ea996f42e8eca89db6352c0a58a2a1c/src/filemanagerframe.cpp#L909-L919 . You could update this to check if the file ends with a known video or image file extension and launch the relevant program.
