### ISSUE TITLE
Please add option for password in CLI

### ISSUE THREAD

**Issue by diow** [allanrbo/filesremote#3]
would it be possible to add -p flag to pass on password in command use? This would be 100 times more useful for anyone in web industry as we are used to WinSCP app which has plenty of not used stuff in there. Thanks

**Comment by allanrbo** [comment]
Hi @diow . I've added the `--password` option in release 1.4 now. Enjoy!

**Comment by diow** [comment]
Ahh thanks that is lovely! We need this because using keepass we can pass password directly to the app so it allows instantaneous access to files without need to type login and password.

**Comment by diow** [comment]
I'll check the 1.5 release and let you know if there are any problems! I have few people that will be pleased to use this on mac

**Comment by allanrbo** [comment]
Great! Hope they'll enjoy it!

**Comment by diow** [comment]
From what I have heard back the only things that we have missing from this is multi selection of the files (to download / upload) and permission modification on the remote directory. Don't worry if you haven't got time for that but it would be fab if that would be in it. Other than that it is superb, works as needed.
