### ISSUE TITLE
Align use of `.ssh/config` better with the openssh client

### ISSUE THREAD

**Issue by allanrbo** [allanrbo/filesremote#4]
Continuation of #1 based on ideas from @abulka .

Should match on the `HostName` field rather than the `Host` field as currently.

Should be able to use connect to hosts using the `Host` field as aliases.

Should be able to pull username and port from the config too. And possibly other params?

**Comment by allanrbo** [comment]
Hey @abulka . Made release 1.5 now with the improvements you suggested. Hope it works as expected this time!

**Comment by abulka** [comment]
Yes it now works as expected - thank you so much!
