### ISSUE TITLE
filesremote window has no size | macos

### ISSUE THREAD

**Issue by ktnk-dev** [allanrbo/filesremote#7]
platform: `MacOS 10.14.6`
version: `1.6`

im using my mac with external display, and often run filesremote on external display. but when i don't have external display connected, window still creates on "external desktop" but it does not exists, and window don't have any size, i cant move it to my macbook's display. 

[video with bug? demonstration](https://cdn.discordapp.com/attachments/718076798398627934/949300706832175195/2022-03-04_16-36-36.mp4)

[video how to temporary fix](https://cdn.discordapp.com/attachments/718076798398627934/949303598234370048/2022-03-04_16-52-28.mp4)

**Comment by allanrbo** [comment]
Thanks for the report! I was able to repro it on my Mac (I usually don't use an external display on that machine, so that's why I hadn't noticed this problem till now). Fixed in version 1.7.

**Comment by ktnk-dev** [comment]
sorry for long response. thanks a lot! ✨
