### ISSUE TITLE
Support wildcard host in ~\.ssh\config

### ISSUE THREAD

**Issue by Himura2la** [allanrbo/filesremote#8]
Hi there! Looks like this great app does not understand the defaults, defined like this:

```
Host *
    User ansible
    IdentityFile ~/.ssh/id_ed25519
```

**Comment by Himura2la** [comment]
somewhere here, I suppose

https://github.com/allanrbo/filesremote/blob/master/src/hostdesc.cpp#L139-L143

**Comment by Himura2la** [comment]
I've been looking at this place, but was not absolutely sure that I understand how it works. Is there any strong reason why we can't extract the `cur_host == this->display_host_ || cur_host.empty()` part into a local variable defined right before the if/else cascade?

**Comment by allanrbo** [comment]
Good point about pulling out the condition. I have done that now. That part of the code isn't very elegant...

Implemented a really simple support for just `Host *` now. Hopefully that will fulfill some people's needs. Didn't have time to do a full fledged version for things like
 * `Host *.example.com`
 * `Host *.example.*`
 * `Host somehost.*.com`
 * `Match host host1.com,host2.com`

Those would be nice to have in the future.
